spring:
  profiles:
    active: dev
  application:
    name: seata-bank1

---
spring:
  profiles: dev
  application:
    name: seata-bank1
  datasource:
    url: jdbc:mysql://localhost:3306/seata-bank1?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8081
mybatis-plus:
  mapper-locations: calsspath:mapper/*.xml