spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: seata-bank2
  datasource:
    url: jdbc:mysql://localhost:3306/seata-bank2?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: cb196225-eceb-4f3e-a609-74308a80e165
        enabled: true
server:
  port: 8082
mybatis-plus:
  mapper-locations: calsspath:mapper/*.xml